version: '3.1'

volumes:
  zero-redis:
  zero-database:

networks:
  laravel:

services:

  nginx:
    networks:
      - laravel
    build:
      context: ./nginx
    container_name: zero-nginx
    ports:
      - "8088:80"
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
      - ${NGINX_CONF_FILE}:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgresql

  redis:
    container_name: zero-redis
    volumes:
      - 'zero-redis:/data'
    ports:
      - "63790:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
    image: library/redis:6.2.1-alpine
    networks:
      - laravel

  composer:
    build:
      context: ./composer
    container_name: zero-composer
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
    depends_on:
      - php
    user: laravel
    networks:
      - laravel
    entrypoint: [ 'composer' ]

  npm:
    image: node:13.7
    container_name: zero-npm
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
    entrypoint: [ 'npm' ]

  php:
    networks:
      - laravel
    build:
      context: ./php
    container_name: zero-php
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    ports:
      - "9000:9000"

  postgresql:
    networks:
      - laravel
    container_name: zero-pgdb
    restart: unless-stopped
    tty: true
    ports:
      - "54326:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - zero-database:/var/lib/postgresql/data/
    image: library/postgres:13.2-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  artisan:
    build:
      context: ./php
    container_name: zero-artisan
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    depends_on:
      - postgresql
    working_dir: ${APP_PATH_CONTAINER}
    user: laravel
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    networks:
      - laravel